# Generated by Django 4.2.9 on 2024-02-08 01:47

from django.db import migrations, models
import django.db.models.deletion
import myclass.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3)),
                ('to_day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('coach', models.ForeignKey(default=myclass.models.default_coach, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accounts.coachprofile')),
            ],
            options={
                'verbose_name_plural': 'Availabilities',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=255)),
                ('apt', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('available_online', models.BooleanField(default=False)),
                ('at_student_convenience', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MyClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('fees', models.DecimalField(decimal_places=0, max_digits=6)),
                ('open_for_booking', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('availability', models.ManyToManyField(related_name='classes', to='myclass.availability')),
                ('category', models.ForeignKey(default=myclass.models.my_default_category, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='myclass.category')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coached_classes', to='accounts.coachprofile')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='myclass', to='myclass.location')),
                ('students', models.ManyToManyField(blank=True, related_name='enrolled_classes', to='accounts.basicprofile')),
            ],
        ),
    ]
