# Generated by Django 4.2.9 on 2024-01-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclass', '0003_alter_myclass_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name_plural': 'Availabilities'},
        ),
        migrations.AddField(
            model_name='myclass',
            name='open_for_booking',
            field=models.BooleanField(default=True),
        ),
    ]
