# Generated by Django 4.2.9 on 2024-01-27 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myclass', '0001_initial'),
        ('accounts', '0014_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('class_reviewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myclass.myclass')),
            ],
        ),
    ]
