# Generated by Django 4.2.9 on 2024-01-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_category_myclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='qualification_documents',
            field=models.FileField(blank=True, null=True, upload_to='qualifications/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('coach', 'Coach')], default='student', max_length=10),
        ),
    ]
