# Generated by Django 4.2.9 on 2024-01-27 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('myclass', '0001_initial'),
        ('accounts', '0014_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='class_booked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myclass.myclass'),
        ),
        migrations.AddField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
