# Generated by Django 4.2.9 on 2024-01-28 00:14

from django.db import migrations, models
import django.db.models.deletion
import myclass.models


class Migration(migrations.Migration):

    dependencies = [
        ('myclass', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myclass',
            name='categories',
        ),
        migrations.AddField(
            model_name='myclass',
            name='category',
            field=models.ForeignKey(default=myclass.models.my_default_category, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='myclass.category'),
        ),
        migrations.AlterField(
            model_name='myclass',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
