# Generated by Django 4.2.9 on 2024-01-29 00:21

from django.db import migrations, models
import django.db.models.deletion
import myclass.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_profile_picture_and_more'),
        ('myclass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday')], max_length=3)),
                ('to_day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday')], max_length=3)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=255)),
                ('apt', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('available_online', models.BooleanField(default=False)),
                ('at_student_convenience', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='myclass',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='myclass',
            name='dates_times',
        ),
        migrations.RemoveField(
            model_name='myclass',
            name='duration',
        ),
        migrations.AddField(
            model_name='myclass',
            name='category',
            field=models.ForeignKey(default=myclass.models.my_default_category, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='myclass.category'),
        ),
        migrations.AddField(
            model_name='myclass',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_classes', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='myclass',
            name='fees',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='myclass',
            name='availability',
            field=models.ManyToManyField(related_name='classes', to='myclass.availability'),
        ),
        migrations.AlterField(
            model_name='myclass',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myclass.location'),
        ),
    ]
