# Generated by Django 4.2.9 on 2024-01-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclass', '0002_remove_myclass_categories_myclass_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclass',
            name='duration',
            field=models.DurationField(),
        ),
    ]
